// Generated by CoffeeScript 1.3.2
(function() {
  var config, source;

  source = /app\.coffee$/.test(process.argv[1]) ? './src/' : './lib/';

  config = require('./config');

  require(source + 'server')(config);

}).call(this);
